sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install pymodbus pymodbus3 pyserial
- pip install flake8
- pip install python-coveralls
script:
- coverage run -m unittest
- flake8 .
after_success:
- coverage report
- coveralls

