sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install mock
- pip install flake8
- pip install python-coveralls
script:
- coverage run --source=fatek -m unittest discover
- flake8 .
after_success:
- coverage report
- coveralls

